version: "3.8"
services:
  postgres:
      image: postgres:17-alpine
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=admin
        - POSTGRES_USER=admin
        - POSTGRES_DB=test_db
      networks:
        - app-network
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - postgres

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - app-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

volumes:
  redis_data:
  cloudbeaver_data:

networks:
  app-network:
    driver: bridge