export const DEFAULT_BOARD = {
  hex: { width: 224, height: 256 },
  diceVals: [
    Math.floor(Math.random() * (12 - 2 + 1)) + 2,
    Math.floor(Math.random() * (12 - 2 + 1)) + 2,
    Math.floor(Math.random() * (12 - 2 + 1)) + 2,
    Math.floor(Math.random() * (12 - 2 + 1)) + 2,
  ],
  hexes: [
    { resource: "wood", coords: { q: 1, r: 0 } },
    { resource: "brick", coords: { q: 2, r: 0 } },
    { resource: "wheat", coords: { q: 3, r: 0 } },
    { resource: "wheat", coords: { q: 0, r: 1 } },
    { resource: "sheep", coords: { q: 1, r: 1 } },
    { resource: "brick", coords: { q: 2, r: 1 } },
    { resource: "stone", coords: { q: 3, r: 1 } },
    { resource: "brick", coords: { q: -1, r: 2 } },
    { resource: "wood", coords: { q: 0, r: 2 } },
    { resource: "desert", coords: { q: 1, r: 2 } },
    { resource: "sheep", coords: { q: 2, r: 2 } },
    { resource: "stone", coords: { q: 3, r: 2 } },
    { resource: "wheat", coords: { q: -1, r: 3 } },
    { resource: "wood", coords: { q: 0, r: 3 } },
    { resource: "sheep", coords: { q: 1, r: 3 } },
    { resource: "stone", coords: { q: 2, r: 3 } },
    { resource: "wood", coords: { q: -1, r: 4 } },
    { resource: "sheep", coords: { q: 0, r: 4 } },
    { resource: "wheat", coords: { q: 1, r: 4 } },
  ],
};
